# Generated by Django 2.2.7 on 2021-01-02 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210102_1715'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phone',
            old_name='phone',
            new_name='phone_num',
        ),
    ]
